<ns0:test-suite xmlns:ns0="urn:model.allure.qatools.yandex.ru" start="1581402779643" stop="1581402779677">
  <name>Scripts</name>
  <labels/>
  <test-cases>
    <test-case start="1581402779643" status="passed" stop="1581402779648">
      <description>
        计算两个数之和等于第三个数   a+b=c
        :param a:
        :param b:
        :param c:
        :return:
        </description>
      <name>test_sum.TestSum.test_s[3-2-5]</name>
      <attachments/>
      <labels>
        <label name="severity" value="normal"/>
        <label name="thread" value="2472-MainThread"/>
        <label name="host" value="DESKTOP-J2VM852"/>
        <label name="framework" value="pytest"/>
        <label name="language" value="cpython3"/>
      </labels>
      <steps/>
    </test-case>
    <test-case start="1581402779649" status="passed" stop="1581402779651">
      <description>
        计算两个数之和等于第三个数   a+b=c
        :param a:
        :param b:
        :param c:
        :return:
        </description>
      <name>test_sum.TestSum.test_s[2-1-3]</name>
      <attachments/>
      <labels>
        <label name="severity" value="normal"/>
        <label name="thread" value="2472-MainThread"/>
        <label name="host" value="DESKTOP-J2VM852"/>
        <label name="framework" value="pytest"/>
        <label name="language" value="cpython3"/>
      </labels>
      <steps/>
    </test-case>
    <test-case start="1581402779651" status="failed" stop="1581402779677">
      <description>
        计算两个数之和等于第三个数   a+b=c
        :param a:
        :param b:
        :param c:
        :return:
        </description>
      <name>test_sum.TestSum.test_s[5-4-6]</name>
      <failure>
        <message>AssertionError: assert (5 + 4) == 6</message>
        <stack-trace>self = &lt;Scripts.test_sum.TestSum object at 0x0000024F5873F208&gt;, a = 5, b = 4, c = 6

    @pytest.mark.parametrize("a,b,c", get_yaml())
    def test_s(self, a, b, c):
        """
            计算两个数之和等于第三个数   a+b=c
            :param a:
            :param b:
            :param c:
            :return:
            """
        print("\n{}+{}={}".format(a, b, c))
        # 断言
&gt;       assert a + b == c
E       assert (5 + 4) == 6

Scripts\test_sum.py:43: AssertionError</stack-trace>
      </failure>
      <attachments/>
      <labels>
        <label name="severity" value="normal"/>
        <label name="thread" value="2472-MainThread"/>
        <label name="host" value="DESKTOP-J2VM852"/>
        <label name="framework" value="pytest"/>
        <label name="language" value="cpython3"/>
      </labels>
      <steps/>
    </test-case>
  </test-cases>
</ns0:test-suite>
